import type { TextItem } from 'pdfjs-dist/types/src/display/api';
import type { PdfTextLayer, PdfTextPort } from '@/core/ports/pdf-text';
import { installPdfDomStubs } from './dom-stubs';

/**
 * The text a PDF already contains, when it contains any.
 *
 * This exists because of a measurement rather than a hunch. Of the eight PDFs in the test
 * set, six carry a real text layer: they were produced by a kupah portal or a hospital
 * system as PDFs, never printed, never photographed. For those six, "OCR" is the wrong verb
 * entirely — the characters are sitting in the file. Reading them is exact, costs
 * milliseconds, needs no model, and cannot misread a Hebrew glyph because it is not reading
 * glyphs.
 *
 * Which makes this the first thing to try on any PDF, and OCR the fallback for the ones that
 * turn out to be pictures of paper.
 */

/**
 * Below this many characters a page is treated as having no usable text layer.
 *
 * Scanned PDFs are rarely empty: a scanner stamps a footer, a portal adds a watermark, and
 * an OCR'd-once-badly file leaves fragments. Accepting those would mean returning a
 * watermark instead of a lab result and never invoking OCR at all — the worst failure here,
 * because it looks like success. The value is per page and deliberately generous: a real
 * page of a medical document runs to hundreds of characters.
 */
const MIN_CHARS_PER_PAGE = 40;

/**
 * What this adapter returns is the port's own shape (`core/ports/pdf-text.ts`), kept as an
 * alias so the name this file has always used still resolves.
 */
export type TextLayerResult = PdfTextLayer;

/**
 * Characters a Hebrew medical document is made of: Hebrew, ASCII, digits, punctuation,
 * whitespace, and the handful of typographic marks these files use.
 */
const EXPECTED = /[֐-׿ -~\s‐-‧ -ÿ]/;

/**
 * Does this text layer decode to real characters, or to glyph indices?
 *
 * A real failure mode, found in this app's own test set. One referral PDF — generated by a
 * hospital system — embeds a subset font with a broken `ToUnicode` map, so pdfjs falls back
 * to glyph ids and every Hebrew letter arrives shifted into the IPA Extensions block:
 * `ʤʮʥʹʸʤ` where the file says `הרשומה`, each character exactly 0x330 below where it belongs.
 *
 * It is silently destructive. The Latin runs in such a file — `LAPAROSCOPY`, procedure codes,
 * the record number — decode perfectly, so the result looks like a partial success and scores
 * 100% precision against a correct reference while carrying none of the Hebrew. Left
 * undetected it would put a lab result's worth of mojibake into the search index and report
 * a text layer where there is effectively none.
 *
 * The offset is a property of one font subset, not a standard, so un-shifting it would fix
 * this file and break the next one. Rejecting the layer and rasterising is the answer that
 * generalises: OCR reads the pixels, which were always correct.
 */
function looksLikeRealText(text: string): boolean {
  const meaningful = [...text].filter((c) => !/\s/.test(c));
  if (meaningful.length < 20) return true; // too little to judge; the page-count gate decides

  const expected = meaningful.filter((c) => EXPECTED.test(c)).length;
  return expected / meaningful.length >= 0.8;
}

/**
 * Reassemble a page's text items into lines.
 *
 * pdfjs hands back positioned fragments in content-stream order, which for Hebrew is neither
 * reading order nor visual order — a right-aligned line can arrive in pieces. Grouping by
 * vertical position and then sorting each line by x descending puts RTL text back the way a
 * person reads it. Without this the output is technically complete and effectively unusable
 * for the search index it feeds.
 */
function itemsToText(items: TextItem[]): string {
  const lines = new Map<number, { x: number; str: string }[]>();

  for (const item of items) {
    if (!item.str) continue;
    // transform is [a, b, c, d, e, f]; e and f are the translation, i.e. x and y.
    const y = Math.round(item.transform[5]);
    const x = item.transform[4];
    // Rounded to the nearest 2pt: glyphs on one visual line rarely share an exact baseline
    // once superscripts and mixed font sizes are involved.
    const key = Math.round(y / 2) * 2;
    const line = lines.get(key) ?? [];
    line.push({ x, str: item.str });
    lines.set(key, line);
  }

  return [...lines.entries()]
    .sort(([a], [b]) => b - a) // top of the page first: PDF y grows upward
    .map(([, fragments]) =>
      fragments
        .sort((a, b) => b.x - a.x) // rightmost first, which is where a Hebrew line starts
        .map((f) => f.str)
        .join('')
        .replace(/\s+/g, ' ')
        .trim(),
    )
    .filter(Boolean)
    .join('\n');
}

/**
 * Pull the embedded text out of a PDF. Returns empty text for a scanned one, which is the
 * signal to rasterise and OCR instead.
 */
export async function readPdfTextLayer(data: Uint8Array): Promise<TextLayerResult> {
  /*
   * Imported here rather than at the top of the file, for two reasons that both come from
   * pdfjs doing real work at module scope.
   *
   * The stubs have to be in place *before* it loads or it throws on a `new DOMMatrix()` in
   * its own top-level code — see `dom-stubs.ts` for the production failure this comes from.
   * A static import is hoisted above every statement in this module, so there is no line
   * this file could put the call on that would run first.
   *
   * And a route that never touches a PDF now never loads pdfjs at all, which is a megabyte
   * or so off the cold start of every other page in the app.
   */
  installPdfDomStubs();
  const { getDocument } = await import('pdfjs-dist/legacy/build/pdf.mjs');

  // pdfjs transfers the buffer it is given and leaves the caller's copy detached, which
  // silently empties the bytes for anyone reading the same file afterwards — the rasteriser,
  // in this pipeline. A copy costs a megabyte and avoids a genuinely baffling bug.
  // The loading task owns the worker and is the thing with a `destroy`; releasing the
  // document alone leaves a worker thread alive.
  const task = getDocument({ data: new Uint8Array(data), useSystemFonts: true });
  const doc = await task.promise;

  try {
    const pages: string[] = [];
    let pagesWithText = 0;

    for (let n = 1; n <= doc.numPages; n++) {
      const page = await doc.getPage(n);
      const content = await page.getTextContent();
      const text = itemsToText(content.items.filter((i): i is TextItem => 'str' in i));
      if (text.length >= MIN_CHARS_PER_PAGE) pagesWithText++;
      pages.push(text);
      page.cleanup();
    }

    const text = pages.filter(Boolean).join('\n\n');

    return {
      text,
      // Every page, including the empty ones: the caller asking for "the first page" means
      // the document's first page, not the first page that happened to carry text.
      pages,
      pagesWithText,
      pageCount: doc.numPages,
      decodable: looksLikeRealText(text),
    };
  } finally {
    await task.destroy();
  }
}

/** The same function behind the port the modules depend on (DESIGN.md §2). */
export class PdfJsTextLayer implements PdfTextPort {
  readTextLayer(data: Uint8Array): Promise<PdfTextLayer> {
    return readPdfTextLayer(data);
  }
}
