import type { AnyContext } from '@/core/context/space-context';

/**
 * All LLM work goes through here, server-side only. The adapter is responsible for
 * logging call *metadata* — model, tokens, latency, cost — and never the prompt or the
 * completion, which contain health data (DESIGN.md §7.1).
 */

/** What a scanned document can arrive as. Widened beyond images once PDFs landed. */
export const SUPPORTED_IMAGE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/gif',
  'image/webp',
] as const;

export type SupportedImageType = (typeof SUPPORTED_IMAGE_TYPES)[number];
export const PDF_TYPE = 'application/pdf';

export function isSupportedScanType(mimeType: string): boolean {
  return mimeType === PDF_TYPE || SUPPORTED_IMAGE_TYPES.includes(mimeType as SupportedImageType);
}

export interface ScanFile {
  data: Uint8Array;
  /** One of SUPPORTED_IMAGE_TYPES, or application/pdf. */
  mimeType: string;
}

export interface ExtractionRequest {
  /**
   * The pages of one document, in order. Several because a letter photographed as two
   * images is still one document, and the fields have to be extracted across all of it —
   * the date on page one, the signature on page two. They go into a single call rather
   * than one call per page, so the model sees the whole thing at once.
   */
  files: readonly ScanFile[];
  /** JSON Schema the model must fill. Validated by the caller before use. */
  schema: Record<string, unknown>;
  instructions: string;
}

export interface LlmUsage {
  model: string;
  tokensIn: number;
  tokensOut: number;
}

export interface LlmResult<T> {
  value: T;
  usage: LlmUsage;
}

/**
 * The same extraction, from text that has already been read off the page.
 *
 * It exists because a PDF generated by a portal or a hospital system *already contains its
 * characters* — measured, 135 of the 149 documents in the first bulk import. Sending those to
 * a vision model means paying it to look at a picture of text the file was handing over for
 * free, and to re-read it slightly wrong.
 *
 * The judgment half still needs a model: which of three dates on a discharge letter is the
 * document's date, whether the letter asks the reader to do something. That is what this
 * asks for, and only that.
 */
export interface TextExtractionRequest {
  text: string;
  /** JSON Schema the model must fill. Validated by the caller before use. */
  schema: Record<string, unknown>;
  instructions: string;
}

export interface LlmPort {
  /** OCR + structured field extraction in a single call, from an image or a PDF (M1). */
  extractFromDocument<T>(ctx: AnyContext, request: ExtractionRequest): Promise<LlmResult<T>>;
  /** Structured field extraction from text the caller already has. See above. */
  extractFromText<T>(ctx: AnyContext, request: TextExtractionRequest): Promise<LlmResult<T>>;
  /** Free-form completion for summaries (M4) and research answers (M5). */
  complete(ctx: AnyContext, prompt: string, opts?: { maxTokens?: number }): Promise<LlmResult<string>>;
}
