import { createHash, randomUUID } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { readInSpace } from '@/core/db/unit-of-work';
import { getFileStorage } from '@/core/container';
import { systemContext } from '@/core/context/space-context';
import { readPdfTextLayer } from '@/adapters/pdf/text-layer';
import {
  extractFromScan,
  extractFromText,
  isStorableDocumentType,
  saveDocument,
  type ExtractedFields,
} from '@/modules/documents';

/**
 * Bulk-importing a folder of medical documents.
 *
 * The app's own upload path is one document at a time by construction: `scanDocument` treats
 * every file you hand it as a *page* of one document, caps you at ten of them, and caps the
 * whole thing at 2.8 MB because a server action carries the file back as base64. None of that
 * is wrong for a phone, and all of it is wrong for a folder of 166 files. This runs
 * server-side, so the body limit does not exist here at all.
 *
 * Two rungs, because a measurement said so. Of the 149 PDFs in the folder this was written
 * for, 135 already carry a decodable text layer — they were generated by a kupah portal or a
 * hospital system, never printed. For those, the characters are in the file, and sending them
 * to a vision model would be paying it to look at a picture of text it was being handed for
 * free, and to re-read it slightly wrong.
 *
 *   1. PDF with a usable text layer  →  read it, then one *text* call for the judgment fields
 *   2. anything else                 →  the ordinary vision path, unchanged
 *
 * It is idempotent through a ledger keyed on the SHA-256 of each file's bytes. There is no
 * dedup anywhere in `modules/documents` — nothing hashes, nothing checks — so without this a
 * second run would file all 166 documents again. Keep the ledger; it is what makes a partial
 * run resumable, which matters because this costs a model call per document.
 *
 *   npm run import:documents -- --dir "C:\path\to\folder" --space <uuid>
 *   npm run import:documents -- --dir "…" --space <uuid> --dry-run
 *   npm run import:documents -- --dir "…" --space <uuid> --limit 5
 *
 * The ledger and the report are written beside the source folder, never into the repository:
 * they carry document names, which are health data.
 */

export interface Args {
  dir: string;
  space: string;
  dryRun: boolean;
  limit: number;
  ledger: string;
  /** Substring filter on the file name. For re-running the handful that failed. */
  match?: string;
}

function parseArgs(): Args {
  const argv = process.argv.slice(2);
  const value = (flag: string) => {
    const at = argv.indexOf(flag);
    return at >= 0 ? argv[at + 1] : undefined;
  };

  const dir = value('--dir');
  const space = value('--space');
  if (!dir || !space) {
    console.error(
      'Usage: npm run import:documents -- --dir <folder> --space <spaceId>' +
        ' [--dry-run] [--limit N] [--match <substring>] [--ledger <file>]',
    );
    process.exit(2);
  }

  return {
    dir,
    space,
    dryRun: argv.includes('--dry-run'),
    limit: Number(value('--limit') ?? Number.POSITIVE_INFINITY),
    // Beside the documents, not in the repo: it lists their names.
    ledger: value('--ledger') ?? path.join(dir, '.healthapp-import-ledger.json'),
    match: value('--match'),
  };
}

const MEDIA_TYPES: Record<string, string> = {
  '.pdf': 'application/pdf',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
};

interface LedgerEntry {
  hash: string;
  documentId: string;
  route: 'text-layer' | 'vision';
  at: string;
}

type Ledger = Record<string, LedgerEntry>;

async function readLedger(file: string): Promise<Ledger> {
  try {
    return JSON.parse(await readFile(file, 'utf8')) as Ledger;
  } catch {
    return {};
  }
}

/**
 * Does this PDF's own text layer carry the document, or only a scanner's footer?
 *
 * Same rule the archived benchmark settled on: most pages must carry text before the file is
 * trusted to have read itself. A scanned bundle with one generated cover page would otherwise
 * return the cover and silently drop the twelve pages that matter — which reads as success.
 */
function usableTextLayer(layer: { decodable: boolean; pagesWithText: number; pageCount: number; text: string }) {
  if (!layer.decodable) return false;
  if (!layer.text.trim()) return false;
  return layer.pagesWithText >= Math.ceil(layer.pageCount * 0.6);
}

export interface Outcome {
  file: string;
  status: 'imported' | 'skipped' | 'failed';
  route?: 'text-layer' | 'vision';
  documentId?: string;
  fields?: Pick<ExtractedFields, 'name' | 'docDate' | 'hospital' | 'doctor'>;
  detail?: string;
  ms?: number;
}

export async function importFolder(args: Args): Promise<Outcome[]> {
  // A system context, as the backfills use: this is not a person acting, and every write is
  // still space-bound.
  const ctx = systemContext(args.space, randomUUID());

  /*
   * The existence check has to go through `readInSpace`, not a bare `db.select()`.
   *
   * RLS keys off `app.current_space_id`, which `readInSpace` sets and a direct query does not
   * — so a plain select returns zero rows for a space that exists perfectly well, and this
   * script would refuse to run against every id it was ever given. The isolation is working;
   * the query was wrong.
   */
  const space = await readInSpace(ctx, (repos) => repos.space.get());
  if (!space) {
    console.error(`No such space: ${args.space}`);
    process.exit(2);
  }
  console.log(`space: ${space.name}`);

  /*
   * Prove storage works before spending anything on extraction.
   *
   * `saveDocument` extracts first and uploads second, so without this a space whose Google
   * account is not connected produces one model call per document and stores none of them —
   * discovered on file 166, having paid for all of them. `ensureFolder` is idempotent and the
   * import creates this folder anyway, so the check costs a round trip and no side effect the
   * run was not going to have.
   */
  if (!args.dryRun) {
    try {
      await getFileStorage().ensureFolder(ctx, 'HealthApp');
    } catch (err) {
      console.error(`Storage is not usable for this space: ${err instanceof Error ? err.message : err}`);
      console.error('Connect Google Drive for this space and run again. Nothing was extracted.');
      process.exit(2);
    }
  }

  const ledger = await readLedger(args.ledger);

  /*
   * The script's own output lives beside the documents by default, so it has to skip it.
   *
   * Without this, a second run reads the report it wrote on the first, calls it an
   * unsupported file, and exits non-zero — a failure that is entirely the script's own doing
   * and looks exactly like a document that could not be imported. The `.docx` and `.html` in
   * a real folder must still be reported: those are the user's documents and they need to
   * know the import skipped them.
   */
  const ledgerName = path.basename(args.ledger);
  const ownArtifact = (name: string) =>
    name === ledgerName || /^import-report-\d+\.json$/.test(name);

  const entries = (await readdir(args.dir, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && !entry.name.startsWith('.'))
    .map((entry) => entry.name)
    .filter((name) => !ownArtifact(name))
    .filter((name) => !args.match || name.includes(args.match))
    .sort();

  console.log(`${entries.length} file(s) in ${args.dir}`);
  console.log(`ledger: ${args.ledger} (${Object.keys(ledger).length} already imported)`);
  if (args.dryRun) console.log('DRY RUN — nothing will be written.\n');

  const outcomes: Outcome[] = [];
  let done = 0;

  for (const name of entries) {
    if (done >= args.limit) {
      console.log(`\nStopping at --limit ${args.limit}. ${entries.length - outcomes.length} file(s) untouched.`);
      break;
    }

    const full = path.join(args.dir, name);
    const extension = path.extname(name).toLowerCase();
    const mimeType = MEDIA_TYPES[extension];

    if (!mimeType || !isStorableDocumentType(mimeType)) {
      outcomes.push({ file: name, status: 'failed', detail: `unsupported type (${extension || 'none'})` });
      console.log(`SKIP  ${name} — unsupported type`);
      continue;
    }

    const data = new Uint8Array(await readFile(full));
    const hash = createHash('sha256').update(data).digest('hex');

    if (ledger[hash]) {
      outcomes.push({ file: name, status: 'skipped', documentId: ledger[hash].documentId, detail: 'already imported' });
      console.log(`SKIP  ${name} — already imported as ${ledger[hash].documentId}`);
      continue;
    }

    const startedAt = performance.now();
    try {
      let fields: ExtractedFields;
      let route: 'text-layer' | 'vision';

      if (mimeType === 'application/pdf') {
        const layer = await readPdfTextLayer(data);
        if (usableTextLayer(layer)) {
          fields = await extractFromText(ctx, layer.text);
          route = 'text-layer';
        } else {
          fields = (await extractFromScan(ctx, [{ data, mimeType }])).fields;
          route = 'vision';
        }
      } else {
        fields = (await extractFromScan(ctx, [{ data, mimeType }])).fields;
        route = 'vision';
      }

      const ms = Math.round(performance.now() - startedAt);

      if (args.dryRun) {
        outcomes.push({ file: name, status: 'imported', route, ms, fields: summarize(fields) });
        console.log(`DRY   ${name} [${route}] → ${fields.name} · ${fields.docDate ?? 'no date'}  (${ms}ms)`);
        done++;
        continue;
      }

      const document = await saveDocument(ctx, {
        fields,
        // One file in, one file stored. `combinePages` is for a letter photographed page by
        // page; here every file already *is* a whole document.
        file: { data, mimeType, extension: extension.slice(1) },
        pageCount: 1,
        proposed: fields as unknown as Record<string, unknown>,
      });

      ledger[hash] = { hash, documentId: document.id, route, at: new Date().toISOString() };
      await writeFile(args.ledger, JSON.stringify(ledger, null, 2), 'utf8');

      outcomes.push({ file: name, status: 'imported', route, documentId: document.id, ms, fields: summarize(fields) });
      console.log(`OK    ${name} [${route}] → ${fields.name} · ${fields.docDate ?? 'no date'}  (${ms}ms)`);
      done++;
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      outcomes.push({ file: name, status: 'failed', detail, ms: Math.round(performance.now() - startedAt) });
      console.log(`FAIL  ${name} — ${detail}`);
    }
  }

  /* --- the report ------------------------------------------------------------- */

  const imported = outcomes.filter((o) => o.status === 'imported');
  const failed = outcomes.filter((o) => o.status === 'failed');
  const skipped = outcomes.filter((o) => o.status === 'skipped');
  const viaText = imported.filter((o) => o.route === 'text-layer').length;

  console.log('\n--- summary ---');
  console.log(`imported: ${imported.length}  (${viaText} via text layer, ${imported.length - viaText} via vision)`);
  console.log(`skipped:  ${skipped.length}`);
  console.log(`failed:   ${failed.length}`);
  for (const f of failed) console.log(`  FAILED  ${f.file} — ${f.detail}`);

  // Fields nobody could extract are the review list: a document with no date is invisible on
  // the calendar, and one with no institution is hard to find later. Both are now correctable
  // on the file screen, which is the point of having built that first.
  const missingDate = imported.filter((o) => !o.fields?.docDate).length;
  const missingHospital = imported.filter((o) => !o.fields?.hospital).length;
  console.log(`\nneeds a human: ${missingDate} without a date, ${missingHospital} without an institution`);

  if (!args.dryRun && imported.length > 0) {
    const reportPath = path.join(path.dirname(args.ledger), `import-report-${Date.now()}.json`);
    await writeFile(reportPath, JSON.stringify(outcomes, null, 2), 'utf8');
    console.log(`\nPer-document report (contains document names — keep it out of the repo):\n  ${reportPath}`);
  }

  return outcomes;
}

async function main() {
  const outcomes = await importFolder(parseArgs());

  /*
   * pdfjs tears its worker down asynchronously even after `task.destroy()` resolves, and
   * calling `process.exit()` while one of those handles is mid-close aborts the process with
   * a libuv assertion — after all the work is done, which is the worst moment to lose the
   * exit code. Yielding the loop first lets the close callbacks run. Observed on Windows
   * against Node 24; the ledger is written per document, so a run that died here was never
   * going to lose data, only its status.
   */
  await new Promise((resolve) => setTimeout(resolve, 250));
  process.exit(outcomes.some((o) => o.status === 'failed') ? 1 : 0);
}

const summarize = (fields: ExtractedFields) => ({
  name: fields.name,
  docDate: fields.docDate,
  hospital: fields.hospital,
  doctor: fields.doctor,
});

/*
 * Only when run as a script. `verify:import` imports `importFolder` directly to exercise the
 * ledger against fake ports, and an unguarded `main()` would have that import parse argv and
 * start a real import.
 */
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
